linkPrefix = "/cacp-contracts"
compiler = "0.4.7-develop.2016.12.14+commit.f8fe6e4f.Darwin.appleclang"
name = "@digix/cacp-contracts"
license = "BSD-3-Clause"
version = "0.0.2"
description = "Contract Access Control"
author = "DigixGlobal"
buildTime = 2016-12-27T18:29:28.872Z
target = "scripts/doxity"
src = "contracts/*"
dir = "pages/docs"
source = "https://github.com/DigixGlobal/doxity-gatsby-starter-project/archive/37f63a26c2664c31f4463a49af939ddb6e2181e7.tar.gz"
out = "docs"

[interaction]
network = "2"
providerUrl = "https://morden.infura.io/ftFX2a6rGHbiA45c6m0r"